/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package evidencija.view;

import evidencija.controller.ObradaEvidencija;
import evidencija.controller.ObradaOdjel;
import evidencija.controller.ObradaOsoba;
import evidencija.controller.ObradaZaposlenik;
import evidencija.model.Zaposlenik;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author jbalog8
 */
public class ZaposlenikovProzor extends javax.swing.JFrame {

   
    private ObradaZaposlenik obrada;

    /**
     * Creates new form ZaposlenikovProzor
     */
    public ZaposlenikovProzor() {

        initComponents();
        obrada = new ObradaZaposlenik();
        
        ucitaj();
        

    }

    public void ucitaj() {
        
       
        DefaultListModel<Zaposlenik> m = new DefaultListModel<>();
        List<Zaposlenik> entiteti = obrada.read();
        
 
       
      
        for(Zaposlenik z : entiteti){
            if(!postojiZaposlenik(m, z)){
                txtImePrezime.setText(z.getIme() + "  " +  z.getPrezime());
                 m.addElement(z);
            }
            txtImePrezime.getText();
            
        }
       
        
    }
    
    private boolean postojiZaposlenik(DefaultListModel<Zaposlenik>z,Zaposlenik p){
        for(int i = 0;i<z.size();i++){
            if(z.get(i).getSifra().equals(p.getSifra())){
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnKrajRada = new javax.swing.JButton();
        btnPocetakRada = new javax.swing.JButton();
        txtImePrezime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DOBRO DOŠAO/LA");

        btnKrajRada.setText("KRAJ RADA");

        btnPocetakRada.setText("POČETAK RADA");
        btnPocetakRada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPocetakRadaActionPerformed(evt);
            }
        });

        txtImePrezime.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtImePrezime.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPocetakRada, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(btnKrajRada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtImePrezime))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtImePrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPocetakRada, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnKrajRada, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPocetakRadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPocetakRadaActionPerformed
        
    }//GEN-LAST:event_btnPocetakRadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKrajRada;
    private javax.swing.JButton btnPocetakRada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtImePrezime;
    // End of variables declaration//GEN-END:variables

}
